### ISSUE TITLE
Deprecated call to sha1 methods

### ISSUE THREAD

**Issue by thibmaek** [jingweno/ccat#41]
```console
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/jingweno/homebrew-ccat/ccat.rb:6:in `<class:Ccat>'
Please report this to the jingweno/ccat tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/jingweno/homebrew-ccat/ccat.rb:6:in `<class:Ccat>'
Please report this to the jingweno/ccat tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/jingweno/homebrew-ccat/ccat.rb:6:in `<class:Ccat>'
Please report this to the jingweno/ccat tap!
```

**Comment by jingweno** [comment]
Please use the official ccat formula in homebrew: https://github.com/Homebrew/homebrew-core/blob/master/Formula/ccat.rb#L5.

**Comment by jingweno** [comment]
Let me know if you have more problems. Closing.
